# Generated by Django 4.2.1 on 2023-05-16 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Dryness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=155)),
                ('tastes_like', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=155)),
                ('geo_code_city', models.CharField(max_length=155)),
                ('country', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Varietal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('image', models.CharField(max_length=155)),
                ('description', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='WineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='VarietalRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acidity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiterabbitapi.acidity')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiterabbitapi.body')),
                ('dryness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiterabbitapi.dryness')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varietal_regions', to='whiterabbitapi.varietal')),
                ('varietal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiterabbitapi.varietal')),
            ],
        ),
        migrations.AddField(
            model_name='varietal',
            name='wine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiterabbitapi.winetype'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
