# Generated by Django 4.2.1 on 2023-05-17 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whiterabbitapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varietalregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varietal_regions', to='whiterabbitapi.region'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritedWine', to='whiterabbitapi.customer')),
                ('varietal_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winos', to='whiterabbitapi.varietalregion')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(related_name='customers', through='whiterabbitapi.Favorite', to='whiterabbitapi.varietalregion'),
        ),
    ]
