# Generated by Django 4.2.1 on 2023-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiterabbitapi', '0003_message_customer_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='messages',
            new_name='received_messages',
        ),
        migrations.AddField(
            model_name='customer',
            name='sent_messages',
            field=models.ManyToManyField(related_name='messagesent', to='whiterabbitapi.message'),
        ),
    ]
