# Generated by Django 4.2.1 on 2023-05-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whiterabbitapi', '0006_alter_message_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('vintage', models.IntegerField()),
                ('image', models.CharField(max_length=155)),
                ('link', models.CharField(max_length=155)),
                ('varietal_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiterabbitapi.varietalregion')),
            ],
        ),
    ]
